GET http://localhost:8000/user/
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Y1ODY3OTEzOWRlYmEwZTNmNzNiNCIsImlhdCI6MTY0MDk5MzYxMX0.4jbgoluviUzDgQu-egLKKVG6T7ajpZov8FNuvudgLgw"
}

###

POST http://localhost:8000/user/signup/
Content-Type: application/json

{
    "username": "nltuong",
    "password": "245678",
    "fullname": "Nguyen Lam Tuong",
    "email": "nltuong19@apcs.fitus.edu.vn",
    "phoneNumber": "263636363"
}

###

POST http://localhost:8000/user/signin/
Content-Type: application/json

{
    "username": "pvphat",
    "password": "645321"
}

###

POST http://localhost:8000/user/change_password/
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Y1ODY3OTEzOWRlYmEwZTNmNzNiNCIsImlhdCI6MTY0MDk5MzYxMX0.4jbgoluviUzDgQu-egLKKVG6T7ajpZov8FNuvudgLgw",
    "oldPassword": "123456",
    "newPassword": "645321"
}

###

POST http://localhost:8000/user/upload_avatar/
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Y1ODY3OTEzOWRlYmEwZTNmNzNiNCIsImlhdCI6MTY0MDk5MzYxMX0.4jbgoluviUzDgQu-egLKKVG6T7ajpZov8FNuvudgLgw"
}

###
POST http://localhost:8000/user/update/
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Y1ODY3OTEzOWRlYmEwZTNmNzNiNCIsImlhdCI6MTY0MDk5MzYxMX0.4jbgoluviUzDgQu-egLKKVG6T7ajpZov8FNuvudgLgw",
    "phoneNumber": "1234556687",
    "about": "need to get fit"
}

###

POST http://localhost:8000/user/update_request/
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2Y1ODY3OTEzOWRlYmEwZTNmNzNiNCIsImlhdCI6MTY0MDk5MzYxMX0.4jbgoluviUzDgQu-egLKKVG6T7ajpZov8FNuvudgLgw"
}